# This file is used by the Thunderstore CLI to build and publish your mod to Thunderstore. https://github.com/thunderstore-io/thunderstore-cli

[config]
schemaVersion = "0.0.1"

[package]
namespace = "NepuShiro" # TODO: Change this to the team you're uploading the mod to on Thunderstore
name = "RMLModSettings" # Change this to your mod's name, no spaces or special characters, max 128 characters
versionNumber = "1.0.0" # Change this to your mod's version, must be in semantic versioning format (e.g. 1.0.0, 2.1.3, 0.1.0-alpha.1), Only read during manual usage of tcli.
description = "Lets you edit your RML mod settings in the BepisModSettings tab of the dashboard." # TODO: Change this to your mod's description, max 250 characters
websiteUrl = "https://github.com/NepuShiro/RMLModSettings" # TODO: Change this to your mod's website/repository, or leave blank
containsNsfwContent = false

# List any dependencies your mod has here, in the format "namespace-modname" = "version-constraint"
[package.dependencies] 
ResoniteModding-BepisLoader = "1.4.1"
ResoniteModding-BepisModSettings = "1.1.1"
ResoniteModding-BepisLocaleLoader = "1.0.0"
ResoniteModding-BepisResoniteWrapper = "1.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

# Copy the compiled DLL to the plugins folder in the mod package
[[build.copy]]
source = "./RMLModSettings/bin/Release/RMLModSettings.dll"
target = "plugins/RMLModSettings/"

# Include the PDB file for better debugging support
[[build.copy]]
source = "./RMLModSettings/bin/Release/RMLModSettings.pdb"
target = "plugins/RMLModSettings/"

[[build.copy]]
source = "./RMLModSettings/Locale"
target = "plugins/RMLModSettings/Locale"

# Uncomment the following lines to include CHANGELOG file in your mod package. https://wiki.thunderstore.io/mods/updating-a-package#changelog
# [[build.copy]]
# source = "./CHANGELOG.md"
# target = "/"

# Uncomment the following line to include LICENSE file in your mod package, if you have one.
# [[build.copy]]
# source = "./LICENSE"
# target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = [ "mods", "dashboard", "misc", ] # TODO: Change this to your mod's categories, see https://thunderstore.io/api/experimental/community/resonite/category/ for a list of available categories
